package mockhttp

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"math"
	mathrand "math/rand"
	"mime"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"mock/restclient"
)

var placeholderPattern = regexp.MustCompile(`\{\{\$([A-Za-z_][A-Za-z0-9_]*)}}`)

func statusFromVariables(variables map[string]string) int {
	raw, ok := variables["status"]
	if !ok {
		return http.StatusOK
	}
	status, err := strconv.Atoi(raw)
	if err != nil || status < 100 || status > 999 {
		return http.StatusOK
	}
	return status
}

func statusAllowsBody(status int) bool {
	return status != http.StatusNoContent && status != http.StatusNotModified && (status < 100 || status >= 200)
}

func responseHeaders(method restclient.Method, filePath string) http.Header {
	headers := method.Headers.Clone()
	if headers.Get("Content-Type") != "" || method.Body != "" || filePath == "" {
		return headers
	}
	if contentType := mime.TypeByExtension(filepath.Ext(filePath)); contentType != "" {
		headers.Set("Content-Type", contentType)
	}
	return headers
}

func renderBody(method restclient.Method, values map[string]string, filePath string, hasFile bool) (string, error) {
	if method.Body == "" {
		if hasFile {
			body, err := os.ReadFile(filePath)
			if err != nil {
				return "", fmt.Errorf("%s: %w", filePath, err)
			}
			return string(body), nil
		}
		return "", nil
	}

	return placeholderPattern.ReplaceAllStringFunc(method.Body, func(match string) string {
		parts := placeholderPattern.FindStringSubmatch(match)
		if len(parts) != 2 {
			return match
		}
		key := parts[1]
		if value, ok := values[key]; ok {
			return value
		}
		if value, ok := method.Variables[key]; ok {
			return value
		}
		return generatedValue(key)
	}), nil
}

func resolveFilePath(method *restclient.Method) (string, bool) {
	raw, ok := method.Variables["file"]
	if !ok {
		return "", false
	}
	raw = strings.TrimSpace(raw)
	if raw == "" || filepath.IsAbs(raw) {
		return "", false
	}
	cleaned := filepath.Clean(raw)
	sep := string(filepath.Separator)
	if cleaned == "." || cleaned == ".." || strings.HasPrefix(cleaned, ".."+sep) {
		return "", false
	}
	return filepath.Join(filepath.Dir(method.Source), cleaned), true
}

func generatedValue(key string) string {
	switch key {
	case "integer":
		return strconv.Itoa(mathrand.Intn(10000))
	case "float":
		return strconv.FormatFloat(math.Round(mathrand.Float64()*10000)/100, 'f', 2, 64)
	case "bool":
		if mathrand.Intn(2) == 0 {
			return "false"
		}
		return "true"
	case "uuid":
		return uuid()
	case "timestamp":
		return strconv.FormatInt(time.Now().Unix(), 10)
	case "isoTimestamp":
		return time.Now().UTC().Format(time.RFC3339)
	case "name":
		return "Alex Morgan"
	case "firstName":
		return "Alex"
	case "lastName":
		return "Morgan"
	case "phone":
		return "555-0100"
	case "user":
		return "amorgan"
	case "email":
		return "alex.morgan@example.com"
	case "url":
		return "https://example.com"
	case "server":
		return "mock"
	case "hash":
		return randomHex(16)
	case "sentence":
		return "This response was generated by mock."
	default:
		return ""
	}
}

func uuid() string {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		return "00000000-0000-4000-8000-000000000000"
	}
	bytes[6] = (bytes[6] & 0x0f) | 0x40
	bytes[8] = (bytes[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", bytes[0:4], bytes[4:6], bytes[6:8], bytes[8:10], bytes[10:16])
}

func randomHex(size int) string {
	bytes := make([]byte, size)
	if _, err := rand.Read(bytes); err != nil {
		return strings.Repeat("0", size*2)
	}
	return hex.EncodeToString(bytes)
}
