### Get with full url
GET http://localhost:8080/user/:id
Content-Type: application/json
AB-RAY: 123abc456def789-LAX
X-Request-ID: request-{{$id}}

{
    "album": "Zenyatta Mondatta",
    "id": {{$id}},
    "name": "{{$name}}",
    "email": "{{$email}}",
    "delay": "{{$delay}}",
    "message": "In a Bottle"
}

### Create user
# $status = 201
POST http://localhost:8080/user
Content-Type: application/json

{
    "id": {{$integer}},
    "delay": "{{$delay}}"
}
