@message = In a Bottle
@ab = 123abc456def789-LAX
@cd = Zenyatta Mondatta

### Get with full url
GET http://localhost:8080/user/:id
Content-Type: application/json
AB-RAY: {{$ab}}
X-Request-ID: {{guid}}_{{id}}

{
    "cd": "{{cd}}",
    "id": {{id}},
    "name": "{{$name}}",
    "email": "{{$email}}",
    "delay": "{{$delay}}",
    "message": "{{$message}}"
}

### Create user
# @status = 201
# @delay = 250ms
POST http://localhost:8080/user
Content-Type: application/json

{
    "id": {{$integer}},
    "delay": "{{$delay}}"
}